// Declarations for the Font Awesome .ttf embedded in the binary (see
// external/fontawesome/VENDORED_FROM.txt). The symbols are defined in
// build/generated/fontawesome_data.cpp, generated by xxd -i from
// external/fontawesome/fontawesome-webfont.ttf (see CMakeLists.txt) --
// there's no source .cpp for this .hpp, it just declares what xxd already
// generates.
#pragma once

extern unsigned char fontawesome_webfont_ttf[];
extern unsigned int fontawesome_webfont_ttf_len;
